import type { CefrLevel, QuizQuestion } from "@/types";

/** Unit themes tailored to each CEFR level so no two levels share a syllabus. */
export const unitTopicsByLevel: Record<CefrLevel, readonly string[]> = {
  A1: [
    "Greetings & Introductions",
    "Numbers, Days & Time",
    "Family & Friends",
    "Food & Drink",
    "My Home",
    "Daily Routine",
    "Colours & Clothes",
    "Places in Town",
  ],
  A2: [
    "Shopping & Money",
    "Travel Plans",
    "Last Weekend",
    "Health & the Body",
    "Jobs & Work",
    "Free Time & Hobbies",
    "Directions & Transport",
    "Weather & Seasons",
    "Comparisons",
    "Making Arrangements",
  ],
  B1: [
    "Opinions & Feelings",
    "Life Experiences",
    "Future Plans",
    "Media & News",
    "Relationships",
    "The Environment",
    "Technology & You",
    "Culture & Traditions",
    "Storytelling",
    "Problem Solving",
    "Work & Careers",
    "Health & Lifestyle",
  ],
  B2: [
    "Debate & Argument",
    "Abstract Ideas",
    "Career & Ambition",
    "Society & Politics",
    "Science & Discovery",
    "Art & Literature",
    "Ethics & Dilemmas",
    "Global Issues",
    "Persuasion",
    "Cause & Effect",
    "Hypotheticals",
    "Narrative Tenses",
    "Formal Writing",
    "Media Analysis",
  ],
  C1: [
    "Nuance & Register",
    "Academic Discourse",
    "Rhetoric & Persuasion",
    "Idiomatic Mastery",
    "Critical Analysis",
    "Professional Communication",
    "Complex Argumentation",
    "Cultural Subtext",
    "Inversion & Emphasis",
    "Cohesion & Cohesive Devices",
    "Hedging & Precision",
    "Discourse Markers",
    "Advanced Collocation",
    "Style & Tone",
    "Paraphrase & Summary",
    "Register Shifting",
  ],
  C2: [
    "Epistemic Modality",
    "Pragmatic Inference",
    "Semantic Nuance",
    "Discourse Architecture",
    "Rhetorical Strategy",
    "Stylistic Register",
    "Metalinguistic Commentary",
    "Argumentation Theory",
    "Critical Discourse Analysis",
    "Intertextuality",
    "Cognitive Metaphor",
    "Pragmatic Presupposition",
    "Information Structure",
    "Prosodic Interpretation",
    "Cross-Cultural Pragmatics",
    "Academic Hedging",
  ],
};

/** Level-appropriate exercises. Lessons pull from the bank matching their course level. */
export const questionBankByLevel: Record<CefrLevel, QuizQuestion[]> = {
  A1: [
    { id: "a1-1", question: "Hello! ___ is your name?", options: ["What", "Where", "Who", "When"], answerIndex: 0, explanation: "'What is your name?' asks for a name." },
    { id: "a1-2", question: "I ___ a student.", options: ["am", "is", "are", "be"], answerIndex: 0, explanation: "With 'I' we use the verb 'am'." },
    { id: "a1-3", question: "___ are you from?", options: ["What", "Where", "Who", "How"], answerIndex: 1, explanation: "'Where' asks about a place or origin." },
    { id: "a1-4", question: "She has two ___.", options: ["cat", "cats", "a cat", "the cat"], answerIndex: 1, explanation: "After a number greater than one, use the plural." },
    { id: "a1-5", question: "It's three ___.", options: ["hour", "o'clock", "time", "clock"], answerIndex: 1, explanation: "We tell the time with 'o'clock'." },
    { id: "a1-6", question: "___ you like coffee?", options: ["Do", "Does", "Are", "Is"], answerIndex: 0, explanation: "Questions with 'you' in the present simple use 'Do'." },
  ],
  A2: [
    { id: "a2-1", question: "Yesterday I ___ to the market.", options: ["go", "went", "gone", "going"], answerIndex: 1, explanation: "'Went' is the past simple of 'go'." },
    { id: "a2-2", question: "She is ___ than her brother.", options: ["tall", "taller", "tallest", "more tall"], answerIndex: 1, explanation: "Short adjectives form the comparative with '-er'." },
    { id: "a2-3", question: "There ___ some milk in the fridge.", options: ["is", "are", "be", "am"], answerIndex: 0, explanation: "'Milk' is uncountable, so it takes 'is'." },
    { id: "a2-4", question: "We ___ watch TV last night.", options: ["don't", "didn't", "doesn't", "aren't"], answerIndex: 1, explanation: "Past negative uses 'didn't' + base verb." },
    { id: "a2-5", question: "How ___ sugar do you want?", options: ["many", "much", "some", "any"], answerIndex: 1, explanation: "Use 'much' with uncountable nouns like 'sugar'." },
    { id: "a2-6", question: "I'm going ___ visit my aunt.", options: ["to", "for", "at", "on"], answerIndex: 0, explanation: "'Going to' + base verb expresses a plan." },
  ],
  B1: [
    { id: "b1-1", question: "She ___ to the gym every morning before work.", options: ["go", "goes", "going", "is go"], answerIndex: 1, explanation: "Third person singular takes 'goes' in the present simple." },
    { id: "b1-2", question: "I haven't seen him ___ last summer.", options: ["for", "since", "from", "during"], answerIndex: 1, explanation: "'Since' marks a specific point in time." },
    { id: "b1-3", question: "If I ___ rich, I would travel the world.", options: ["am", "was", "were", "be"], answerIndex: 2, explanation: "The second conditional uses 'were' for all persons." },
    { id: "b1-4", question: "The meeting has been ___ until next Friday.", options: ["put off", "put on", "put out", "put up"], answerIndex: 0, explanation: "'Put off' is a phrasal verb meaning to postpone." },
    { id: "b1-5", question: "By the time we arrived, the film ___.", options: ["started", "has started", "had started", "starts"], answerIndex: 2, explanation: "Past perfect shows an action finished before another past action." },
    { id: "b1-6", question: "He suggested ___ a short break.", options: ["to take", "taking", "take", "took"], answerIndex: 1, explanation: "'Suggest' is followed by the -ing form." },
  ],
  B2: [
    { id: "b2-1", question: "Hardly ___ she arrived when it started to rain.", options: ["had", "has", "did", "was"], answerIndex: 0, explanation: "'Hardly' triggers inversion with the past perfect: 'Hardly had she...'." },
    { id: "b2-2", question: "I'd rather you ___ smoke in here.", options: ["don't", "didn't", "won't", "not"], answerIndex: 1, explanation: "'Would rather' + subject uses the past form 'didn't'." },
    { id: "b2-3", question: "The project, ___ took months, was a huge success.", options: ["which", "who", "what", "whose"], answerIndex: 0, explanation: "Non-defining clauses about things use 'which'." },
    { id: "b2-4", question: "It's high time we ___ this problem.", options: ["address", "addressed", "addressing", "to address"], answerIndex: 1, explanation: "'It's high time' is followed by the past simple." },
    { id: "b2-5", question: "___ the bad weather, the event went ahead.", options: ["Despite", "Although", "However", "Because"], answerIndex: 0, explanation: "'Despite' is followed by a noun phrase." },
    { id: "b2-6", question: "She denied ___ the confidential document.", options: ["to sign", "signing", "sign", "signed"], answerIndex: 1, explanation: "'Deny' is followed by the -ing form." },
  ],
  C1: [
    { id: "c1-1", question: "No sooner had we sat down ___ the phone rang.", options: ["than", "then", "when", "that"], answerIndex: 0, explanation: "'No sooner... than' is the fixed correlative structure." },
    { id: "c1-2", question: "___ be any complications, contact the office immediately.", options: ["Should there", "If there", "Were there", "Had there"], answerIndex: 0, explanation: "'Should there be' is a formal inverted first conditional." },
    { id: "c1-3", question: "His argument was ___ flawed, lacking any real evidence.", options: ["fundamentally", "fundamental", "foundation", "fund"], answerIndex: 0, explanation: "An adverb ('fundamentally') is needed to modify the adjective 'flawed'." },
    { id: "c1-4", question: "She spoke with such eloquence ___ the room fell silent.", options: ["that", "so", "which", "as"], answerIndex: 0, explanation: "'Such + noun + that' introduces a result clause." },
    { id: "c1-5", question: "The new policy is tantamount ___ a complete ban.", options: ["to", "with", "of", "for"], answerIndex: 0, explanation: "The collocation is 'tantamount to' (equivalent to)." },
    { id: "c1-6", question: "Not only ___ the deadline, but he also exceeded expectations.", options: ["he met", "did he meet", "he did meet", "met he"], answerIndex: 1, explanation: "'Not only' at the start of a clause forces subject-auxiliary inversion." },
  ],
  C2: [
    { id: "c2-1", question: "The findings are ___ consistent with the prevailing theory.", options: ["broadly", "broad", "breadth", "broaden"], answerIndex: 0, explanation: "An adverb ('broadly') modifies the adjective 'consistent'." },
    { id: "c2-2", question: "Had the evidence been ___, the verdict would have differed.", options: ["substantive", "substantially", "substantiate", "substantiated"], answerIndex: 3, explanation: "The past participle 'substantiated' fits the passive construction." },
    { id: "c2-3", question: "The author's argument is not ___ but rather exploratory.", options: ["definitive", "definition", "definitely", "definitively"], answerIndex: 0, explanation: "An adjective ('definitive') is needed after 'is not'." },
    { id: "c2-4", question: "She spoke with ___ that left no room for doubt.", options: ["authority", "authoritative", "authoritatively", "authorised"], answerIndex: 0, explanation: "A noun ('authority') follows the preposition 'with'." },
    { id: "c2-5", question: "The policy, ___ well-intentioned, produced adverse effects.", options: ["however", "although", "being", "notwithstanding"], answerIndex: 3, explanation: "'Notwithstanding' + adjective means 'in spite of'." },
    { id: "c2-6", question: "This phenomenon ___ a reassessment of established paradigms.", options: ["necessitates", "necessity", "necessarily", "necessitated"], answerIndex: 0, explanation: "A verb in the present simple ('necessitates') matches the subject." },
  ],
};
