import {
  ShieldCheck,
  Target,
  ListChecks,
  Boxes,
  CircleSlash,
  CircleCheck,
  Lightbulb,
  TrendingUp,
  TrendingDown,
  Split,
  Crosshair,
  Search,
  Smile,
  Star,
  Gift,
  BadgeCheck,
  Mountain,
  Sparkles,
  UtensilsCrossed,
  Utensils,
  BookOpen,
  Plane,
  Briefcase,
  Cpu,
  HeartPulse,
  Users,
  GraduationCap,
  Home,
  Leaf,
  Shirt,
  Dumbbell,
  Wallet,
  CloudSun,
  PawPrint,
  Building2,
  MessageCircle,
  MessageSquare,
  Palette,
  Zap,
  Droplet,
  Maximize,
  Sun,
  Map,
  HandCoins,
  VolumeX,
  SplitSquareHorizontal,
  ShieldAlert,
  MapPin,
  Tag,
  Trophy,
  Ban,
  Globe,
  Gem,
  Hourglass,
  Columns2,
  KeyRound,
  FastForward,
  Fingerprint,
  Eye,
  ScanSearch,
  HelpCircle,
  Milestone,
  Wrench,
  Link,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/cn";

const iconMap: Record<string, LucideIcon> = {
  ShieldCheck,
  Target,
  ListChecks,
  Boxes,
  CircleSlash,
  CircleCheck,
  Lightbulb,
  TrendingUp,
  TrendingDown,
  Split,
  Crosshair,
  Search,
  Smile,
  Star,
  Gift,
  BadgeCheck,
  Mountain,
  Sparkles,
  UtensilsCrossed,
  Utensils,
  Plane,
  Briefcase,
  Cpu,
  HeartPulse,
  Users,
  GraduationCap,
  Home,
  Leaf,
  Shirt,
  Dumbbell,
  Wallet,
  CloudSun,
  PawPrint,
  Building2,
  MessageCircle,
  MessageSquare,
  Palette,
  Zap,
  Droplet,
  Maximize,
  Sun,
  Map,
  HandCoins,
  VolumeX,
  SplitSquareHorizontal,
  ShieldAlert,
  MapPin,
  Tag,
  Trophy,
  Ban,
  Globe,
  Gem,
  Hourglass,
  Columns2,
  KeyRound,
  FastForward,
  Fingerprint,
  Eye,
  ScanSearch,
  HelpCircle,
  Milestone,
  Wrench,
  Link,
};

interface WordIllustrationProps {
  icon: string;
  color: string;
  size?: "sm" | "md" | "lg" | "xl";
  className?: string;
}

const sizeClasses = {
  sm: "size-10 rounded-xl [&_svg]:size-5",
  md: "size-14 rounded-2xl [&_svg]:size-7",
  lg: "size-20 rounded-2xl [&_svg]:size-10",
  xl: "size-28 rounded-3xl [&_svg]:size-14",
} as const;

/** A gradient tile with a representative icon — the word's visual illustration. */
export function WordIllustration({ icon, color, size = "md", className }: WordIllustrationProps) {
  const Icon = iconMap[icon] ?? BookOpen;
  return (
    <div
      aria-hidden
      className={cn(
        "flex shrink-0 items-center justify-center bg-gradient-to-br text-white shadow-soft",
        color,
        sizeClasses[size],
        className,
      )}
    >
      <Icon />
    </div>
  );
}