import { useCallback, useEffect, useRef, useState } from "react";
import { useUser } from "@/store/auth";

export type AiStatus = "loading" | "ai" | "fallback";

export interface AiContent<T> {
  items: T[];
  status: AiStatus;
  /** Re-fetch a fresh set of rounds (used by "Play again"/"New round"). */
  refresh: () => void;
}

/**
 * Loads game content generated by the AI for a specific game, falling back to
 * static `fallback` if generation is unavailable or slow. The game engine is
 * untouched — this only swaps the round source.
 */
export function useAiContent<T>(
  game: string,
  fallback: T[],
  opts?: { level?: string; count?: number; timeoutMs?: number },
): AiContent<T> {
  const userLevel = useUser().level;
  const level = opts?.level ?? userLevel;
  const [status, setStatus] = useState<AiStatus>("loading");
  const [items, setItems] = useState<T[]>(fallback);
  const [nonce, setNonce] = useState(0);
  const fallbackRef = useRef(fallback);
  fallbackRef.current = fallback;

  useEffect(() => {
    const controller = new AbortController();
    const timer = window.setTimeout(() => controller.abort(), opts?.timeoutMs ?? 10000);
    let cancelled = false;
    setStatus("loading");
    (async () => {
      try {
        const res = await fetch("/api/games/generate", {
          method: "POST",
          headers: { "content-type": "application/json" },
          signal: controller.signal,
          body: JSON.stringify({ game, level, count: opts?.count }),
        });
        if (!res.ok) throw new Error(`fetch ${res.status}`);
        const data = (await res.json()) as { items?: unknown[] };
        if (cancelled) return;
        const generated = (data.items ?? []) as T[];
        if (generated.length > 0) {
          setItems(generated);
          setStatus("ai");
        } else {
          setItems(fallbackRef.current);
          setStatus("fallback");
        }
      } catch {
        if (!cancelled) {
          setItems(fallbackRef.current);
          setStatus("fallback");
        }
      } finally {
        window.clearTimeout(timer);
      }
    })();
    return () => {
      cancelled = true;
      controller.abort();
      window.clearTimeout(timer);
    };
  }, [game, level, nonce, opts?.count, opts?.timeoutMs, opts?.level]);

  const refresh = useCallback(() => setNonce((n) => n + 1), []);
  return { items, status, refresh };
}

/** Thin shell shown while AI content loads (or falls back). */
export function AiLoadingShell({ label = "Generating a fresh round…" }: { label?: string }) {
  return (
    <div className="flex min-h-64 flex-col items-center justify-center gap-3 py-8 text-center">
      <div className="h-8 w-8 animate-spin rounded-full border-2 border-muted border-t-primary" aria-hidden />
      <p className="text-sm text-muted-foreground">{label}</p>
    </div>
  );
}