import type { CefrLevel } from "@/types";

export type GrammarCategory =
  | "Present Tenses"
  | "Past Tenses"
  | "Future Tenses"
  | "Conditionals"
  | "Structures"
  | "Modals"
  | "Nouns & Articles"
  | "Adjectives & Adverbs"
  | "Verb Patterns";

export interface GrammarStructure {
  affirmative: string;
  negative: string;
  question: string;
}

export interface GrammarUse {
  rule: string;
  example: string;
}

export interface GrammarTopic {
  id: string;
  title: string;
  level: CefrLevel;
  category: GrammarCategory;
  summary: string;
  structure: GrammarStructure;
  uses: GrammarUse[];
  signalWords: string[];
  examples: string[];
  exceptions: string[];
}

export const grammarTopics: GrammarTopic[] = [
  // ─────────────────────────────── PRESENT ───────────────────────────────
  {
    id: "present-simple",
    title: "Present Simple",
    level: "A1",
    category: "Present Tenses",
    summary: "Facts, habits, routines and permanent situations.",
    structure: {
      affirmative: "Subject + base verb (+ s/es for he/she/it)",
      negative: "Subject + do/does + not + base verb",
      question: "Do/Does + subject + base verb?",
    },
    uses: [
      { rule: "Habits and routines", example: "She drinks coffee every morning." },
      { rule: "Permanent facts and general truths", example: "Water boils at 100 °C." },
      { rule: "Timetables and schedules (fixed future)", example: "The train leaves at 6 p.m." },
      { rule: "States and feelings (with stative verbs)", example: "I love this song." },
      { rule: "Permanent situations", example: "He works at a hospital." },
      { rule: "Future timetables (with a future time expression)", example: "The flight departs at 9 a.m. tomorrow." },
    ],
    signalWords: ["always", "usually", "often", "sometimes", "never", "every day", "on Mondays", "rarely", "seldom", "hardly ever"],
    examples: [
      "I work in a hospital.",
      "He doesn't eat meat.",
      "Do they live near here?",
      "She always arrives on time.",
      "We don't have class on Sundays.",
      "Does he speak Spanish?",
      "The sun rises in the east.",
      "They play football every weekend.",
    ],
    exceptions: [
      "Third person singular adds -s: work → works.",
      "Verbs ending in -o, -ss, -sh, -ch, -x add -es: go → goes, watch → watches.",
      "Consonant + y → -ies: study → studies (but play → plays after a vowel).",
      "'Be' and modal verbs do not use do/does.",
      "Stative verbs (know, want, believe, own) are normally not used in the continuous.",
      "Have (possession) → has: She has a car (not 'She is having').",
    ],
  },
  {
    id: "present-continuous",
    title: "Present Continuous",
    level: "A1",
    category: "Present Tenses",
    summary: "Actions happening now or around now, and fixed future arrangements.",
    structure: {
      affirmative: "Subject + am/is/are + verb-ing",
      negative: "Subject + am/is/are + not + verb-ing",
      question: "Am/Is/Are + subject + verb-ing?",
    },
    uses: [
      { rule: "Actions in progress right now", example: "She is reading a book." },
      { rule: "Temporary situations around now", example: "I'm staying with friends this week." },
      { rule: "Fixed future arrangements", example: "We're meeting John tomorrow." },
      { rule: "Changing or developing situations", example: "The climate is getting warmer." },
      { rule: "Annoying habits (with 'always')", example: "He's always losing his keys." },
      { rule: "Temporary jobs", example: "She's working at a café this summer." },
    ],
    signalWords: ["now", "right now", "at the moment", "currently", "today", "this week", "Look!", "Listen!", "at present", "just now"],
    examples: [
      "They are playing football.",
      "He isn't working today.",
      "Are you listening to me?",
      "I'm reading an interesting book at the moment.",
      "The children are sleeping right now.",
      "She's always complaining about the weather.",
    ],
    exceptions: [
      "Spelling: drop silent -e before -ing: make → making.",
      "One-syllable CVC words double the final consonant: run → running, sit → sitting.",
      "-ie → -ying: lie → lying, die → dying.",
      "Stative verbs (like, know, understand) are usually not used here.",
      "Some verbs change meaning: 'I'm thinking' (process) vs 'I think' (opinion).",
      "Verbs like want, need, prefer are stative: I want (not 'I am wanting').",
    ],
  },
  {
    id: "present-perfect",
    title: "Present Perfect",
    level: "B1",
    category: "Present Tenses",
    summary: "A past action with a present result or an unfinished time period.",
    structure: {
      affirmative: "Subject + have/has + past participle",
      negative: "Subject + have/has + not + past participle",
      question: "Have/Has + subject + past participle?",
    },
    uses: [
      { rule: "Life experiences (unspecified time)", example: "I have visited Japan." },
      { rule: "Past action with a present result", example: "She has lost her keys (she can't get in now)." },
      { rule: "Unfinished time periods", example: "We have studied a lot this week." },
      { rule: "Recent actions with 'just', 'already', 'yet'", example: "They have just arrived." },
      { rule: "Actions that started in the past and continue now", example: "I have lived here for five years." },
      { rule: "With 'so far' and 'up to now'", example: "So far, we have learned 200 words." },
    ],
    signalWords: ["ever", "never", "just", "already", "yet", "since", "for", "recently", "so far", "up to now", "lately", "this week/month/year"],
    examples: [
      "Have you ever been abroad?",
      "He has already finished his homework.",
      "I haven't seen that film yet.",
      "She has worked here since 2019.",
      "We have been friends for a long time.",
      "They haven't visited us lately.",
      "I've just eaten lunch.",
    ],
    exceptions: [
      "Use 'since' with a point in time, 'for' with a duration: since 2020 / for three years.",
      "Do NOT use with finished time words (yesterday, last year) — use Past Simple instead.",
      "American English often prefers Past Simple where British English uses Present Perfect.",
      "'Been' = went and came back; 'gone' = went and is still there.",
      "Use Past Simple for actions at a specific finished time: I saw him yesterday.",
    ],
  },
  {
    id: "present-perfect-continuous",
    title: "Present Perfect Continuous",
    level: "B1",
    category: "Present Tenses",
    summary: "An action that started in the past and is still continuing (emphasis on duration).",
    structure: {
      affirmative: "Subject + have/has + been + verb-ing",
      negative: "Subject + have/has + not + been + verb-ing",
      question: "Have/Has + subject + been + verb-ing?",
    },
    uses: [
      { rule: "Action continuing up to now", example: "I have been studying for three hours." },
      { rule: "Recent activity with visible results", example: "You're tired because you've been running." },
      { rule: "Emphasis on how long, not how many", example: "She has been working here since May." },
      { rule: "Temporary situation that started in the past", example: "They've been living in Madrid since January." },
    ],
    signalWords: ["for", "since", "all day", "all morning", "how long", "lately", "recently", "all the time"],
    examples: [
      "It has been raining all day.",
      "How long have you been waiting?",
      "They haven't been getting along recently.",
      "I've been learning English for ten years.",
      "She looks tired — she's been working hard.",
      "He's been coughing all morning.",
    ],
    exceptions: [
      "Stative verbs use Present Perfect Simple, not continuous: 'I have known him for years' (not 'been knowing').",
      "Use the simple form when the result/quantity matters: 'I've read three books' vs 'I've been reading'.",
      "Don't use with verbs that don't have a continuous form: know, believe, understand.",
    ],
  },
  // ──────────────────────────────── PAST ────────────────────────────────
  {
    id: "past-simple",
    title: "Past Simple",
    level: "A2",
    category: "Past Tenses",
    summary: "Completed actions at a specific finished time in the past.",
    structure: {
      affirmative: "Subject + past form (verb-ed / irregular)",
      negative: "Subject + did + not + base verb",
      question: "Did + subject + base verb?",
    },
    uses: [
      { rule: "Finished actions at a definite time", example: "I visited Rome in 2019." },
      { rule: "A sequence of past events", example: "She woke up, got dressed and left." },
      { rule: "Past habits (also 'used to')", example: "We played outside every summer." },
      { rule: "Past states (with stative verbs)", example: "I knew the answer." },
      { rule: "Completed actions with a finished time", example: "They watched a film last night." },
    ],
    signalWords: ["yesterday", "last week", "ago", "in 2010", "then", "when I was young", "last night", "two days ago", "at that time"],
    examples: [
      "They watched a film last night.",
      "He didn't call me.",
      "Did you enjoy the party?",
      "I went to the store yesterday.",
      "She finished her homework an hour ago.",
      "We met in 2015.",
      "He didn't come to school last Monday.",
    ],
    exceptions: [
      "Regular verbs add -ed; consonant + y → -ied: study → studied.",
      "One-syllable CVC verbs double the consonant: stop → stopped.",
      "Many common verbs are irregular: go → went, buy → bought, see → saw.",
      "After 'did' the main verb returns to its base form: 'Did you go?' (not 'went').",
      "'Be' has two forms: was (I/he/she/it) and were (you/we/they).",
      "Irregular verbs don't follow a pattern — they must be memorized.",
    ],
  },
  {
    id: "past-continuous",
    title: "Past Continuous",
    level: "A2",
    category: "Past Tenses",
    summary: "An action in progress at a moment in the past, often interrupted.",
    structure: {
      affirmative: "Subject + was/were + verb-ing",
      negative: "Subject + was/were + not + verb-ing",
      question: "Was/Were + subject + verb-ing?",
    },
    uses: [
      { rule: "Action in progress at a past time", example: "At 8 p.m. I was having dinner." },
      { rule: "A longer action interrupted by a shorter one", example: "I was cooking when the phone rang." },
      { rule: "Two parallel past actions", example: "She was reading while he was cooking." },
      { rule: "Background description in a story", example: "The sun was shining and birds were singing." },
      { rule: "An action in progress when another started", example: "When I arrived, they were watching TV." },
    ],
    signalWords: ["while", "as", "when", "at that moment", "all day yesterday", "at 8 p.m.", "this time yesterday"],
    examples: [
      "They were waiting for the bus.",
      "He wasn't listening.",
      "What were you doing at midnight?",
      "I was walking home when it started to rain.",
      "She was talking on the phone while I was cooking.",
      "The kids were playing in the garden all afternoon.",
    ],
    exceptions: [
      "Same -ing spelling rules as Present Continuous.",
      "Use 'when' + Past Simple for the interruption, 'while' + Past Continuous for the long action.",
      "Stative verbs normally use Past Simple: 'I knew the answer' (not 'was knowing').",
      "Use 'as' for two actions happening at the same time.",
    ],
  },
  {
    id: "past-perfect",
    title: "Past Perfect",
    level: "B1",
    category: "Past Tenses",
    summary: "An action completed before another past action ('the past of the past').",
    structure: {
      affirmative: "Subject + had + past participle",
      negative: "Subject + had + not + past participle",
      question: "Had + subject + past participle?",
    },
    uses: [
      { rule: "Earlier of two past actions", example: "The train had left before we arrived." },
      { rule: "Cause of a past situation", example: "She was upset because she had failed." },
      { rule: "Reported speech (backshift of Past Simple/Present Perfect)", example: "He said he had finished." },
      { rule: "With 'after', 'before', 'by the time'", example: "After she had left, we cleaned up." },
    ],
    signalWords: ["already", "before", "after", "by the time", "just", "never … before", "when", "until"],
    examples: [
      "By 10 a.m. they had sold everything.",
      "I hadn't met him before that day.",
      "Had you eaten when I called?",
      "She had already gone when I arrived.",
      "They left after they had finished dinner.",
      "By the time I got there, the movie had started.",
    ],
    exceptions: [
      "Only needed to show one past action happened before another — a single past action uses Past Simple.",
      "With 'after' the sequence is clear, so Past Simple is often acceptable: 'After she left, we ate.'",
      "Don't use Past Perfect if the order of events is clear from context.",
    ],
  },
  {
    id: "past-perfect-continuous",
    title: "Past Perfect Continuous",
    level: "B2",
    category: "Past Tenses",
    summary: "A continuing action that had been happening before another past moment.",
    structure: {
      affirmative: "Subject + had + been + verb-ing",
      negative: "Subject + had + not + been + verb-ing",
      question: "Had + subject + been + verb-ing?",
    },
    uses: [
      { rule: "Duration of an action up to a past point", example: "She had been working there for ten years when it closed." },
      { rule: "Past cause with continuous emphasis", example: "He was tired because he had been running." },
      { rule: "Repeated past action before another event", example: "They had been visiting that restaurant for years before it closed." },
    ],
    signalWords: ["for", "since", "before", "how long", "all day", "all morning", "by the time"],
    examples: [
      "They had been driving for hours before they stopped.",
      "I hadn't been sleeping well, so I felt exhausted.",
      "How long had you been waiting when the bus came?",
      "She had been teaching for 20 years before she retired.",
      "He was out of breath because he had been running.",
    ],
    exceptions: [
      "Stative verbs take Past Perfect Simple instead: 'had known', not 'had been knowing'.",
      "Use the simple form when a quantity is stated: 'She had written five reports.'",
      "Less common than Past Perfect Simple — use it mainly to emphasize duration.",
    ],
  },
  // ─────────────────────────────── FUTURE ───────────────────────────────
  {
    id: "future-will",
    title: "Future Simple (will)",
    level: "A2",
    category: "Future Tenses",
    summary: "Predictions, instant decisions, promises and offers.",
    structure: {
      affirmative: "Subject + will + base verb",
      negative: "Subject + will + not (won't) + base verb",
      question: "Will + subject + base verb?",
    },
    uses: [
      { rule: "Predictions based on opinion", example: "I think it will rain tomorrow." },
      { rule: "Instant decisions (at the moment of speaking)", example: "I'll help you with that." },
      { rule: "Promises, offers and requests", example: "I'll always love you." },
      { rule: "Facts about the future", example: "She will be 30 next year." },
      { rule: "Threats or warnings", example: "If you don't study, you will fail." },
      { rule: "Willingness to do something", example: "I'll open the window if you're hot." },
    ],
    signalWords: ["tomorrow", "next week", "soon", "in the future", "probably", "I think", "I promise", "I believe"],
    examples: [
      "They will arrive at noon.",
      "He won't come to the party.",
      "Will you marry me?",
      "I think it will be a great movie.",
      "Don't worry, I'll help you.",
      "She will probably call you later.",
    ],
    exceptions: [
      "Use 'going to' (not 'will') for plans already decided and for evidence-based predictions.",
      "After 'if/when/before/after' use the present, not 'will': 'When I get home, I'll call you.'",
      "'Shall' is a formal alternative for I/we, mainly in offers and suggestions: 'Shall we go?'",
      "Won't = will not.",
    ],
  },
  {
    id: "future-going-to",
    title: "Future with 'going to'",
    level: "A2",
    category: "Future Tenses",
    summary: "Plans and intentions already made, and predictions based on present evidence.",
    structure: {
      affirmative: "Subject + am/is/are + going to + base verb",
      negative: "Subject + am/is/are + not + going to + base verb",
      question: "Am/Is/Are + subject + going to + base verb?",
    },
    uses: [
      { rule: "Plans and intentions decided before speaking", example: "We are going to buy a house." },
      { rule: "Predictions based on present evidence", example: "Look at those clouds — it's going to rain." },
      { rule: "Intentions (personal plans)", example: "I'm going to learn Japanese next year." },
      { rule: "Evidence-based predictions", example: "The road is wet — it's going to rain." },
    ],
    signalWords: ["tonight", "next month", "this weekend", "soon", "in a minute", "look", "watch out"],
    examples: [
      "I'm going to study medicine.",
      "She isn't going to accept the offer.",
      "Are you going to tell him?",
      "It's going to be a great day!",
      "They're going to have a baby.",
      "Look! The car is going to hit that wall!",
    ],
    exceptions: [
      "With verbs of movement, present continuous is often preferred: 'We're going to go' → 'We're going.'",
      "For instant decisions use 'will', not 'going to'.",
      "Going to can also express a prediction based on evidence: 'Look at those clouds — it's going to rain.'",
    ],
  },
  {
    id: "future-continuous",
    title: "Future Continuous",
    level: "B1",
    category: "Future Tenses",
    summary: "An action that will be in progress at a specific future time.",
    structure: {
      affirmative: "Subject + will + be + verb-ing",
      negative: "Subject + will + not + be + verb-ing",
      question: "Will + subject + be + verb-ing?",
    },
    uses: [
      { rule: "Action in progress at a future moment", example: "This time tomorrow I'll be flying to Paris." },
      { rule: "Polite enquiries about plans", example: "Will you be using the car tonight?" },
      { rule: "Expected/planned future events", example: "I'll be seeing her at the meeting." },
      { rule: "Parallel future actions", example: "While I'm cooking, she'll be setting the table." },
    ],
    signalWords: ["this time tomorrow", "at 8 p.m. tomorrow", "in the future", "all day tomorrow", "at noon", "next week"],
    examples: [
      "They'll be waiting for us.",
      "He won't be working next week.",
      "What will you be doing at noon?",
      "I'll be thinking of you while you're away.",
      "This time next year I'll be living in New York.",
      "Will you be using the computer at 3 p.m.?",
    ],
    exceptions: [
      "Stative verbs use Future Simple: 'I'll know soon' (not 'will be knowing').",
      "Use Future Continuous for polite requests: 'Will you be using…?' is softer than 'Will you use…?'",
    ],
  },
  {
    id: "future-perfect",
    title: "Future Perfect",
    level: "B2",
    category: "Future Tenses",
    summary: "An action that will be completed before a specific point in the future.",
    structure: {
      affirmative: "Subject + will + have + past participle",
      negative: "Subject + will + not + have + past participle",
      question: "Will + subject + have + past participle?",
    },
    uses: [
      { rule: "Completed before a future deadline", example: "By 2030 they will have finished the bridge." },
      { rule: "Assumptions about the recent past", example: "She will have arrived by now." },
      { rule: "Completed actions before another future action", example: "By the time you arrive, I'll have cooked dinner." },
    ],
    signalWords: ["by", "by then", "by the time", "before", "in two years", "by next week"],
    examples: [
      "I will have graduated by June.",
      "They won't have left before we get there.",
      "Will you have completed the report by Friday?",
      "By 2025, she will have written three books.",
      "They will have been married for 10 years next month.",
    ],
    exceptions: [
      "After 'by the time' use the present simple: 'By the time you arrive, I'll have cooked dinner.'",
      "Don't confuse with Future Perfect Continuous (emphasizes duration).",
    ],
  },
  {
    id: "future-perfect-continuous",
    title: "Future Perfect Continuous",
    level: "C1",
    category: "Future Tenses",
    summary: "The duration of an action up to a point in the future.",
    structure: {
      affirmative: "Subject + will + have + been + verb-ing",
      negative: "Subject + will + not + have + been + verb-ing",
      question: "Will + subject + have + been + verb-ing?",
    },
    uses: [
      { rule: "How long an action will have continued", example: "By May I will have been working here for ten years." },
      { rule: "Cause of a future situation", example: "He'll be exhausted — he'll have been travelling all night." },
    ],
    signalWords: ["by", "for", "by the time", "in … years' time", "by next year"],
    examples: [
      "By 2026 they will have been building it for a decade.",
      "She won't have been studying long enough to pass.",
      "How long will you have been living here by next year?",
      "By December, I'll have been working here for five years.",
      "They'll have been driving for 12 hours by the time they arrive.",
    ],
    exceptions: [
      "Rare in everyday speech; stative verbs use Future Perfect Simple instead.",
      "Mainly used to emphasize duration rather than completion.",
    ],
  },
  // ────────────────────────── CONDITIONALS ──────────────────────────
  {
    id: "conditionals",
    title: "Conditionals (0–3 & Mixed)",
    level: "B1",
    category: "Conditionals",
    summary: "'If' sentences describing real, possible, unreal and past situations.",
    structure: {
      affirmative: "If + condition clause, + result clause",
      negative: "If + subject + (do not/did not/had not) …, …",
      question: "What will/would happen if …?",
    },
    uses: [
      { rule: "Zero — general truths (if + present, present)", example: "If you heat ice, it melts." },
      { rule: "First — real future (if + present, will)", example: "If it rains, I will stay home." },
      { rule: "Second — unreal present (if + past, would)", example: "If I were rich, I would travel." },
      { rule: "Third — unreal past (if + past perfect, would have)", example: "If I had studied, I would have passed." },
      { rule: "Mixed — past condition, present result", example: "If I had saved money, I would be rich now." },
      { rule: "Unless = if not", example: "Unless you hurry, you'll miss the bus." },
    ],
    signalWords: ["if", "unless", "as long as", "provided that", "in case", "were I to", "had I known", "suppose"],
    examples: [
      "Unless you hurry, you'll miss the train.",
      "If I had known, I would have told you.",
      "Mixed: If I had saved money, I would be rich now.",
      "If I were you, I would accept the offer.",
      "As long as you study, you will pass the exam.",
      "In case it rains, take an umbrella.",
    ],
    exceptions: [
      "Use 'were' for all persons in the second conditional: 'If I were you…'.",
      "Do NOT use 'will' or 'would' in the if-clause.",
      "'Unless' = 'if not'.",
      "Formal inversion can replace 'if': 'Had I known…', 'Were I rich…', 'Should you need…'.",
      "Use 'were' (not 'was') in formal second conditional: 'If I were you'.",
    ],
  },
  // ────────────────────────── STRUCTURES ──────────────────────────
  {
    id: "passive-voice",
    title: "Passive Voice",
    level: "B1",
    category: "Structures",
    summary: "Focus on the action or the receiver rather than who does it.",
    structure: {
      affirmative: "Object + be (correct tense) + past participle (+ by + agent)",
      negative: "Object + be + not + past participle",
      question: "Be + object + past participle?",
    },
    uses: [
      { rule: "The doer is unknown or unimportant", example: "The window was broken." },
      { rule: "Formal, scientific or news writing", example: "The samples were analysed carefully." },
      { rule: "To keep known information first", example: "This bridge was built in 1890." },
      { rule: "General truths and facts", example: "English is spoken in many countries." },
      { rule: "Instructions and processes", example: "First, the ingredients are mixed together." },
    ],
    signalWords: ["by", "is/are made", "was/were done", "has been", "will be", "was built", "were created"],
    examples: [
      "English is spoken here.",
      "The report hasn't been finished.",
      "Were the tickets sold?",
      "The cake was made by my grandmother.",
      "This building was constructed in 1950.",
      "The students were given a test.",
      "Milk is used to make cheese.",
    ],
    exceptions: [
      "Only transitive verbs (with an object) can be passive.",
      "The tense is carried by the verb 'be': is done, was done, has been done, will be done.",
      "Add 'by + agent' only when the doer is important.",
      "Intransitive verbs (arrive, sleep, happen) have no passive.",
      "Some verbs have two passives: 'He gave me a book' → 'I was given a book' or 'A book was given to me'.",
    ],
  },
  {
    id: "reported-speech",
    title: "Reported Speech",
    level: "B2",
    category: "Structures",
    summary: "Telling what someone said, usually with a tense 'backshift'.",
    structure: {
      affirmative: "Subject + said (that) + backshifted clause",
      negative: "Subject + said (that) + subject + didn't …",
      question: "Subject + asked + if/wh- + subject + verb (no inversion)",
    },
    uses: [
      { rule: "Reporting statements", example: "\"I'm tired.\" → He said he was tired." },
      { rule: "Reporting questions (no inversion, no ?)", example: "\"Where do you live?\" → She asked where I lived." },
      { rule: "Reporting commands (tell + to-infinitive)", example: "\"Sit down.\" → He told me to sit down." },
      { rule: "Reporting offers and suggestions", example: "\"Shall I help?\" → He offered to help." },
      { rule: "Reporting promises", example: "\"I'll call you.\" → She promised to call me." },
    ],
    signalWords: ["said", "told", "asked", "explained", "that", "if", "whether", "suggested", "offered", "promised"],
    examples: [
      "\"I will call you.\" → He said he would call me.",
      "\"Have you eaten?\" → She asked if I had eaten.",
      "\"Don't touch it.\" → He warned me not to touch it.",
      "\"Where is the station?\" → He asked where the station was.",
      "\"I'm going to leave.\" → She said she was going to leave.",
      "\"Let's go.\" → He suggested that they go.",
    ],
    exceptions: [
      "Backshift: present → past, past → past perfect, will → would, can → could, must → had to.",
      "Time/place words change: now → then, today → that day, here → there, this → that.",
      "No backshift needed if the statement is still true: 'She said she likes coffee.'",
      "'Say' has no object; 'tell' needs one: say to me / tell me.",
      "Wh-questions keep the word order: 'Where do you live?' → She asked where I lived.",
    ],
  },
  {
    id: "inversion-emphasis",
    title: "Inversion & Emphasis",
    level: "C1",
    category: "Structures",
    summary: "Advanced word order for emphasis, formality and dramatic effect.",
    structure: {
      affirmative: "Negative adverbial + auxiliary + subject + verb",
      negative: "Not until … + did + subject + verb",
      question: "(Structure mirrors question word order)",
    },
    uses: [
      { rule: "After negative adverbials", example: "Never have I seen such a mess." },
      { rule: "After 'hardly/no sooner' with sequence", example: "No sooner had we left than it rained." },
      { rule: "Conditional inversion (formal)", example: "Had I known, I would have helped." },
      { rule: "Cleft sentences for emphasis", example: "It was John who broke it." },
      { rule: "After 'not only … but also'", example: "Not only did she win, but she also set a record." },
      { rule: "After 'only then/after/before'", example: "Only then did I realize the truth." },
    ],
    signalWords: ["never", "rarely", "seldom", "hardly", "no sooner", "not only", "little", "only then", "not until", "at no time"],
    examples: [
      "Not only did she win, but she also set a record.",
      "Little did he know what was coming.",
      "Only after the meeting did I understand.",
      "Never have I been so embarrassed.",
      "Rarely does he arrive on time.",
      "Hardly had I sat down when the phone rang.",
      "Seldom do we get such good news.",
    ],
    exceptions: [
      "Inversion is mostly used in formal or literary English.",
      "The auxiliary carries the tense: 'Never have I…', 'Rarely does she…'.",
      "'Not only … but also' inverts the first clause only.",
      "Don't use inversion after negative words in normal speech: 'I have never seen' is fine.",
    ],
  },
  // ──────────────────────────── MODALS ────────────────────────────
  {
    id: "modal-verbs",
    title: "Modal Verbs",
    level: "B1",
    category: "Modals",
    summary: "Ability, permission, obligation, advice, possibility and deduction.",
    structure: {
      affirmative: "Subject + modal + base verb",
      negative: "Subject + modal + not + base verb",
      question: "Modal + subject + base verb?",
    },
    uses: [
      { rule: "Ability — can/could", example: "She can swim. / He could read at four." },
      { rule: "Obligation — must/have to; advice — should/ought to", example: "You must stop. / You should rest." },
      { rule: "Possibility & deduction — may/might/could/must/can't", example: "He must be tired. / It might rain." },
      { rule: "Permission & requests — can/could/may", example: "May I come in? / Could you help?" },
      { rule: "Past ability — could/was able to", example: "She could swim when she was five." },
      { rule: "Deduction about the past — must have/can't have/might have", example: "He must have forgotten." },
    ],
    signalWords: ["can", "could", "may", "might", "must", "shall", "should", "will", "would", "ought to", "have to", "need to"],
    examples: [
      "You mustn't smoke here.",
      "We should have left earlier.",
      "She can't be serious.",
      "He might come to the party.",
      "You don't have to wear a tie.",
      "Could you pass me the salt?",
      "I must remember to call her.",
      "She must have been tired after the long trip.",
    ],
    exceptions: [
      "Modals take no -s and are followed by the base verb (no 'to'), except 'ought to'.",
      "They have no infinitive or -ing form; use substitutes: 'be able to', 'have to'.",
      "'Must' (personal obligation) vs 'have to' (external rule); 'mustn't' (prohibition) vs 'don't have to' (no obligation).",
      "Past deduction: modal + have + past participle — 'He must have left.'",
      "Needn't = don't have to (no obligation).",
    ],
  },
  // ─────────────────────── NOUNS & ARTICLES ───────────────────────
  {
    id: "articles",
    title: "Articles (a, an, the)",
    level: "A1",
    category: "Nouns & Articles",
    summary: "Using a, an, the and zero article correctly with nouns.",
    structure: {
      affirmative: "a/an + singular countable noun / the + specific noun",
      negative: "no + noun / not a/an + noun",
      question: "Is this a/an …? / Do you have the …?",
    },
    uses: [
      { rule: "Indefinite article (a/an) — first mention, non-specific", example: "I saw a dog in the park." },
      { rule: "The before something specific or already mentioned", example: "The dog was brown." },
      { rule: "No article for general plurals and uncountables", example: "Dogs are friendly. / Water is essential." },
      { rule: "Unique things (the sun, the moon)", example: "The sun rises in the east." },
      { rule: "Superlatives and ordinals (the best, the first)", example: "She is the tallest girl in class." },
      { rule: "Geographical names (rivers, mountains)", example: "The Nile is the longest river." },
    ],
    signalWords: ["a", "an", "the", "this", "that", "some", "every"],
    examples: [
      "I need a pen.",
      "Can you close the door?",
      "She is an engineer.",
      "The Eiffel Tower is in Paris.",
      "I love music.",
      "He is the best student in the class.",
      "There is a cat on the roof.",
      "The cat is black.",
    ],
    exceptions: [
      "Use 'an' before vowel sounds: an apple, an hour (silent h), an umbrella.",
      "Use 'a' before consonant sounds: a university (yoo- sound), a European.",
      "No article: 'I like coffee' (general), but 'I'd like a coffee' (one cup).",
      "No article with most country names: France, Japan (but the USA, the UK).",
      "No article with meals: 'I have breakfast at 8.'",
    ],
  },
  {
    id: "countable-uncountable",
    title: "Countable & Uncountable Nouns",
    level: "A1",
    category: "Nouns & Articles",
    summary: "Understanding which nouns can be counted and which cannot.",
    structure: {
      affirmative: "a/an + countable singular / much/many + noun / a lot of + noun",
      negative: "not many + countable / not much + uncountable / no + noun",
      question: "How many + countable? / How much + uncountable?",
    },
    uses: [
      { rule: "Countable nouns have singular and plural forms", example: "a book → two books" },
      { rule: "Uncountable nouns have no plural form", example: "water, information, furniture, advice" },
      { rule: "Use 'many' with countable, 'much' with uncountable", example: "many students / much water" },
      { rule: "Use 'a few' with countable, 'a little' with uncountable", example: "a few books / a little time" },
      { rule: "Some/any work with both types", example: "some books / some water" },
    ],
    signalWords: ["how many", "how much", "a lot of", "many", "much", "a few", "a little", "some", "any"],
    examples: [
      "How many students are in the class?",
      "There isn't much milk left.",
      "I have a few friends in London.",
      "She gave me some good advice.",
      "We don't have much time.",
      "How much money do you need?",
      "There are many reasons to learn English.",
      "I need some information about the course.",
    ],
    exceptions: [
      "Common uncountable nouns: information, advice, furniture, luggage, homework, news, progress, equipment.",
      "Some nouns are uncountable in English but countable in other languages: bread, rice, sugar.",
      "Use 'a piece of' to count uncountables: a piece of advice, a piece of furniture.",
      "Some nouns can be both: two coffees (cups) / I like coffee (the drink).",
      "Money is uncountable: much money (not 'many moneys').",
    ],
  },
  // ─────────────────── ADJECTIVES & ADVERBS ───────────────────
  {
    id: "comparatives-superlatives",
    title: "Comparatives & Superlatives",
    level: "A2",
    category: "Adjectives & Adverbs",
    summary: "Comparing two or more things using adjective forms.",
    structure: {
      affirmative: "adj-er + than (short) / more + adj (long)",
      negative: "less + adj + than",
      question: "Is this adj-er than that? / Which is the most adj?",
    },
    uses: [
      { rule: "Short adjectives (1 syllable): add -er", example: "She is taller than her brother." },
      { rule: "Long adjectives (3+ syllables): use 'more'", example: "This book is more interesting than that one." },
      { rule: "Superlative: the + adj-est / the most + adj", example: "She is the tallest in the class." },
      { rule: "Irregular: good → better → best", example: "This is the best meal I've ever had." },
      { rule: "Less/more for uncountable nouns", example: "I need less sugar and more water." },
      { rule: "As … as (equal comparison)", example: "She is as tall as her mother." },
    ],
    signalWords: ["than", "the most", "the -est", "less", "more", "as … as", "far", "much", "even", "a lot"],
    examples: [
      "This coffee is hotter than mine.",
      "She is the most intelligent student in the class.",
      "My house is bigger than yours.",
      "This is the worst movie I've ever seen.",
      "He runs faster than anyone else.",
      "This book is less expensive than that one.",
      "She is as smart as her sister.",
      "The weather is getting worse.",
    ],
    exceptions: [
      "Spelling rules: big → bigger, happy → happier, beautiful → more beautiful.",
      "Irregular: good → better → best, bad → worse → worst, far → farther/further → farthest/furthest.",
      "Two-syllable adjectives ending in -y: happy → happier → happiest.",
      "Don't double consonants for two-syllable adjectives: quiet → quieter (not 'quietter').",
      "Use 'the' before superlatives: the best (not 'best').",
    ],
  },
  // ─────────────────── VERB PATTERNS ───────────────────
  {
    id: "gerunds-infinitives",
    title: "Gerunds & Infinitives",
    level: "B1",
    category: "Verb Patterns",
    summary: "When to use verb + -ing (gerund) or verb + to + infinitive.",
    structure: {
      affirmative: "Subject + verb + verb-ing / Subject + verb + to + verb",
      negative: "Subject + verb + not + verb-ing / not + to + verb",
      question: "Do you enjoy + verb-ing? / Would you like to + verb?",
    },
    uses: [
      { rule: "Verbs followed by gerund: enjoy, finish, mind, suggest, avoid", example: "I enjoy reading books." },
      { rule: "Verbs followed by infinitive: want, need, decide, hope, plan", example: "She wants to travel." },
      { rule: "Both with different meanings: stop, remember, try, forget", example: "I stopped smoking. / I stopped to smoke." },
      { rule: "After prepositions, always use gerund", example: "She is interested in learning English." },
      { rule: "Adjective + infinitive: happy to, glad to, surprised to", example: "I'm happy to help you." },
    ],
    signalWords: ["enjoy", "finish", "mind", "want", "decide", "hope", "plan", "interested in", "good at", "without"],
    examples: [
      "I enjoy reading before bed.",
      "She wants to become a doctor.",
      "He finished writing the report.",
      "They decided to move to a new city.",
      "I'm looking forward to meeting you.",
      "She's good at cooking Italian food.",
      "I stopped eating sugar last year.",
      "Remember to lock the door.",
    ],
    exceptions: [
      "Enjoy, avoid, finish, mind, suggest, practice, keep, consider → always gerund.",
      "Want, need, hope, decide, plan, agree, offer, refuse, promise → always infinitive.",
      "Stop, remember, try, forget, regret → can take both (with different meanings).",
      "After prepositions (-ing): 'I'm tired of waiting', 'She left without saying goodbye'.",
      "Go + gerund for activities: go shopping, go swimming, go running.",
    ],
  },
  {
    id: "relative-clauses",
    title: "Relative Clauses",
    level: "B1",
    category: "Structures",
    summary: "Using who, which, that, where, whose to connect clauses.",
    structure: {
      affirmative: "Noun + who/which/that + clause",
      negative: "Noun + who/which/that + don't/doesn't + clause",
      question: "Who/Which/That + verb + noun?",
    },
    uses: [
      { rule: "Who — for people", example: "The man who lives next door is a doctor." },
      { rule: "Which — for things and animals", example: "The book which I read was great." },
      { rule: "That — for people or things (informal)", example: "The car that I bought is red." },
      { rule: "Where — for places", example: "The restaurant where we ate was expensive." },
      { rule: "Whose — possession", example: "The girl whose father is a teacher is in my class." },
      { rule: "When — for times", example: "I remember the day when we first met." },
    ],
    signalWords: ["who", "which", "that", "where", "whose", "when"],
    examples: [
      "The woman who called me is my aunt.",
      "This is the house which Jack built.",
      "The city where I live is beautiful.",
      "The student whose phone rang was embarrassed.",
      "Do you know the man standing over there?",
      "I'll never forget the day when I graduated.",
      "The reason why she left is unknown.",
    ],
    exceptions: [
      "That can replace who/which in defining relative clauses.",
      "Who/which/that can be omitted when they are the object: 'The man (that) I saw was tall'.",
      "Don't omit when they are the subject: 'The man who called is tall' (not 'The man called is tall').",
      "Whose can be used for things: 'the book whose cover is torn'.",
      "Non-defining clauses use commas: 'My brother, who lives in London, is a doctor'.",
    ],
  },
];

export const grammarCategories: GrammarCategory[] = [
  "Present Tenses",
  "Past Tenses",
  "Future Tenses",
  "Conditionals",
  "Structures",
  "Modals",
  "Nouns & Articles",
  "Adjectives & Adverbs",
  "Verb Patterns",
];

export function getGrammarTopic(id: string): GrammarTopic | undefined {
  return grammarTopics.find((t) => t.id === id);
}
